# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# When a release if created, the source and binary artifacts will be attached.

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Attach Release Artifacts to Release
      uses: softprops/action-gh-release@v0.1.14
      if: ${{ github.event_name == 'release' }}
      with:
        files: target/*.jar

